name: Tests
on: [push, pull_request]

jobs:
  actions:
    runs-on: ubuntu-latest
    environment: pypi_token
    permissions:
      id-token: write
    steps:
    - name: Copia repositorio
      uses: actions/checkout@main
    - name: Construye imagen
      run: docker build --tag islasgeci/wrangler .
    - name: Verifica el formato
      run: docker run islasgeci/wrangler make check
    - name: Corre pruebas y evalua cobertura
      run: docker run islasgeci/wrangler make coverage
    - name: Evalua resistencia a mutaciones
      run: docker run islasgeci/wrangler make mutants
    - name: Create/Update tag
      uses: rickstaa/action-create-tag@main
      with:
        tag: "latest"
        message: "Latest release"
        force_push_tag: true
    - name: Set up Python 3.x
      uses: actions/setup-python@main
      with:
        python-version: '3.x'
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
